# Generated by Django 5.0.1 on 2024-12-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="events/audios/"),
        ),
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="events/photos/"),
        ),
        migrations.AddField(
            model_name="event",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="events/videos/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="theme",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="image",
            field=models.ImageField(blank=True, upload_to="themes/"),
        ),
        migrations.DeleteModel(
            name="Media",
        ),
    ]
