# Generated by Django 5.0.1 on 2024-12-07 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0002_event_audio_event_photo_event_video_alter_event_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="event",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="event",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="event",
            name="video",
        ),
        migrations.AddField(
            model_name="event",
            name="media_file",
            field=models.FileField(default="media/placeholder.JPG", upload_to="media/"),
        ),
        migrations.AddField(
            model_name="event",
            name="media_type",
            field=models.CharField(
                choices=[("photo", "Photo"), ("audio", "Audio"), ("video", "Video")],
                default="photo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="theme_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Theme",
        ),
    ]
